logging:
  level:
    org: WARN

spring:
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    defer-datasource-initialization: true
    show-sql: false
    properties:
      hibernate:
        format_sql: true

h2:
  console:
    enabled: true
    
controller:
  hello:
    name:
      default: Manish

springdoc:
  swagger-ui:
    path: /docs
    