server:
  port: 4000

spring:
  datasource:
    url: ${DATASOURCE_URL}
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

h2:
  console:
    enabled: true